export const TYPES = {
    Bot: Symbol('Bot'),
    Client: Symbol('Client'),
    DiscordToken: Symbol('Token'),
    Mongoose: Symbol('Mongoose'),
    MessageDispatcher: Symbol('MessageDispatcher'),
    GuildRepository: Symbol('GuildRepository'),
    GuildService: Symbol('GuildService'),
    RaidTemplateRepository: Symbol('RaidTemplateRepository'),
    RaidTemplateService: Symbol('RaidTemplateService'),
    GuildConfigService: Symbol('GuildConfigService'),
    SetupService: Symbol('SetupService'),
    ClientTools: Symbol('ClientTools'),
    RaidController: Symbol('RaidController'),
    RaidTemplateController: Symbol('RaidTemplateController'),
    RaidManager: Symbol('RaidManager'),
    ConfigController: Symbol('ConfigController'),
    RaidConfigRepository: Symbol('RaidConfigRepository'),
    RealmEyeService: Symbol('RealmEyeService')
};